version: '3.6'

services:
  dyndb:
    build: ./docker/
    environment:
      AWS_ACCESS_KEY_ID: akey
      AWS_SECRET_ACCESS_KEY: skey
      TABLE_NAME: User
      ITEM_NAME: User1
    ports:
    - "8000:8000"
    volumes:
      - ./docker/volumes:/src
